spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:pra # test ??? ??? ??? ??? ???? ???.
    username: sa # username? password? ??? ??? ??
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # ???? query? ???
  application:
    name: pre-practice

logging.level:
  org.hibernate.SQL: debug