spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/test # h2 url
    username: sa
    password:
    driver-class-name: org.h2.Driver

  messages:
    basename: message
    encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  application:
    name: pre-practice

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: debug

jwt:
  secret: cZh9pS213BYk5OcYz1kAH8XC/+DuCBXL8UwGcpBxKwT4kJQ5nVSvnLZMmC5h4YY3QUxvP1wqmfftxxU05VLtAds==
  header: Authorization
  prefix: Bearer
